# Generated by Django 5.0.6 on 2025-07-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrido',
            name='ciudad',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo ($)'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='estado',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='foto',
            field=models.ImageField(upload_to='fotos_recorridos/', verbose_name='Imagen del recorrido'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='km',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Distancia (km)'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='punto_inicio',
            field=models.CharField(max_length=200, verbose_name='Punto de inicio'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='realizado',
            field=models.BooleanField(default=False, verbose_name='¿Ya se realizó?'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='tiempo_estimado',
            field=models.DurationField(verbose_name='Tiempo estimado'),
        ),
    ]
