# Generated by Django 5.0.6 on 2025-08-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0002_alter_recorrido_ciudad_alter_recorrido_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(default=20, verbose_name='Capacidad máxima'),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='cupos_disponibles',
            field=models.PositiveIntegerField(default=20, verbose_name='Cupos disponibles'),
        ),
    ]
