# Generated by Django 5.0.6 on 2025-08-04 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0003_recorrido_capacidad_maxima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorrido',
            name='capacidad_maxima',
        ),
        migrations.RemoveField(
            model_name='recorrido',
            name='cupos_disponibles',
        ),
    ]
