# Generated by Django 5.0.6 on 2025-08-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0004_remove_recorrido_capacidad_maxima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='ruta',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
