# Generated by Django 5.0.6 on 2025-08-04 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['fecha_comentario'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='fotopublicacion',
            options={'verbose_name': 'Foto de publicación', 'verbose_name_plural': 'Fotos de publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
    ]
