# Generated by Django 5.0.6 on 2025-07-09 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_inscripcion_usuario'),
        ('recorridos', '0002_alter_recorrido_ciudad_alter_recorrido_costo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('usuario', 'recorrido')},
        ),
    ]
