# Generated by Django 5.0.6 on 2025-07-09 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_alter_inscripcion_options_and_more'),
        ('recorridos', '0002_alter_recorrido_ciudad_alter_recorrido_costo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('usuario', 'recorrido'), name='unique_usuario_recorrido'),
        ),
    ]
