# Generated by Django 5.0.6 on 2025-08-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_alter_inscripcion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='cantidad_personas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
