# Generated by Django 5.0.6 on 2025-08-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_inscripcion_cantidad_personas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='cantidad_personas',
        ),
    ]
